### ISSUE TITLE
editor crashes first time I hit run, but not second

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#130]
?hack=26e0dc93729c19432804

**Comment by increpare** [comment]
line:
	Text.display(xOffset+95,2+charOffset,dat.patternLength,textCol);


error:
line 530 : RUNTIME ERROR
Unknown error type in line 530:
Error name: TypeError
Javascript Stack:
TypeError: s.charCodeAt is not a function at Function.HxOverrides.cca (http://localhost:8000/webthing.js:1970:12) at Function.Std.parseInt (http://localhost:8000/webthing.js:2837:28) at Function.terrylib_Convert.toint (http://localhost:8000/webthing.js:40907:13) at Function.terrylib_Text.display (http://localhost:8000/webthing.js:42372:81) at Function.Reflect.callMethod (http://localhost:8000/webthing.js:2618:14) at Object.hscript_Interp.call (http://localhost:8000/webthing.js:9063:18) at Object.hscript_Interp.fcall (http://localhost:8000/webthing.js:9060:15) at Object.hscript_Interp.expr (http://localhost:8000/webthing.js:8776:18) at Object.hscript_Interp.expr (http://localhost:8000/webthing.js:8724:15) at Object.hscript_Interp.exprReturn (http://localhost:8000/webthing.js:8633:16)

**Comment by increpare** [comment]
AND, on the second run, note that some of the text is garbled

<img width="177" alt="screen shot 2015-08-31 at 08 56 31" src="https://cloud.githubusercontent.com/assets/465632/9574409/8e0d632a-4fbe-11e5-90cd-0ccae57d4b7a.png">

i guess that's because it's caching stuff between runs? i strongly recommend clearing all caches every time you hit run - not being able to reproduce stuff by recompiling is, I think, bad.

**Comment by increpare** [comment]
replacing
Text.display(xOffset+95,2+charOffset,dat.patternLength,textCol);
with
Text.display(xOffset+95,2+charOffset,Convert.tostring(dat.patternLength),textCol);
fixes the problem for me.

maybe a more helpful error message for typeerrors?

**Comment by increpare** [comment]
works fine now
