### ISSUE TITLE
arrays in hscript don't have a remove method?

### ISSUE THREAD

**Issue by increpare** [increpare/terrylib_online#66]
so, any idea how I can remove an element from an array?

function update() {
  var a = [1,2,3];
  a.Remove(2);
}

RUNTIME ERROR: TypeError: Cannot read property 'apply' of undefined at Function.Reflect.callMethod (http://localhost:8000/webthing.js:1987:13) at Object.hscript_Interp.call (http://localhost:8000/webthing.js:4592:18) at Object.hscript_Interp.fcall (http://localhost:8000/webthing.js:4589:15) at Object.hscript_Interp.expr (http://localhost:8000/webthing.js:4305:18) at Object.hscript_Interp.expr (http://localhost:8000/webthing.js:4253:15) at Object.hscript_Interp.exprReturn (http://localhost:8000/webthing.js:4162:16) at f3 (http://localhost:8000/webthing.js:4394:19) at Function.updatefunction (http://localhost:8000/webthing.js:2021:10) at Function.Webscript.update (http://localhost:8000/webthing.js:2431:14) at Object.Main.update (http://localhost:8000/webthing.js:1785:13)

**Comment by increpare** [comment]
ok this works

function new(){
  var a = [1,2,3];
  var i = a.indexOf(1);
  a.splice(i,1);
  trace(a);
}

this sort of stuff probably needs to be documented, I don't think the hscript website has it documented
